### ISSUE TITLE
Fix accessibility issues: contrast

### ISSUE THREAD

**Issue by Zodiac1978** [roytanck/rt-plugin-report#72]
Modify colors to reach WCAG contrast:

```css
td.pr-risk-high {
  background-color: #fcf0f1;
  color: #b32d2e !important;
}

td.pr-risk-low {
  background-color: #edfaef;
  color: #007017 !important;
}
```

See: https://make.wordpress.org/core/2021/02/23/standardization-of-wp-admin-colors-in-wordpress-5-7/
